// Run from any directory: node scripts/build.mjs. Uses Node.js built-ins only.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createDiagrams } from './diagrams.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const projects = JSON.parse(readFileSync(resolve(root, 'scripts/projects.json'), 'utf8'));
const e = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const bi = (zh, en) => `<span data-lang="zh">${zh}</span><span data-lang="en">${en}</span>`;
const txt = pair => bi(e(pair[0]), e(pair[1]));
const pages = 'https://geemakerlee.github.io/GeeMakerLee/';
mkdirSync(resolve(root, 'docs/projects'), { recursive: true });
createDiagrams(resolve(root, 'docs/assets/diagrams'));

const sections = [
  ['需要解决的问题', 'The problem', 'problem'],
  ['我的工程贡献', 'My contribution', 'work'],
  ['关键设计取舍', 'Design trade-off', 'tradeoff'],
  ['产品视角', 'Product perspective', 'product']
];

function card(p, i) {
  return `<article class="project-card" id="${p.slug}" aria-labelledby="${p.slug}-title">
    <a class="diagram-preview" href="assets/diagrams/${p.slug}.svg" target="_blank" rel="noopener noreferrer"><img src="assets/diagrams/${p.slug}.svg" width="1160" height="660" loading="lazy" alt="${e(p.name)} architecture and data flow"></a>
    <div class="diagram-caption"><span>0${i + 1} / ${txt(['架构与数据流', 'Architecture & data flow'])}</span><a href="assets/diagrams/${p.slug}.svg" target="_blank" rel="noopener noreferrer">${txt(['查看全图 ↗', 'Full-size diagram ↗'])}</a></div>
    <div class="project-copy"><div class="project-name">${e(p.name)}</div><h3 id="${p.slug}-title">${txt(p.title)}</h3>
    <p class="project-summary" data-lens="engineering">${txt(p.focus)}</p><p class="project-summary" data-lens="product">${txt(p.product)}</p>
    <div class="tags">${p.tags.map(t => `<span>${e(t)}</span>`).join('')}</div><div data-gallery="${p.slug}"></div>
    <details><summary>${txt(['阅读项目详情', 'Read the case study'])}</summary><div class="case-details">${sections.map(([zh, en, key]) => `<h4>${txt([zh, en])}</h4><p>${txt(p[key])}</p>`).join('')}<div class="current-state">${txt(p.state)}</div></div></details>
    <a class="case-permalink" href="#${p.slug}">${txt(['分享这个项目 ↗', 'Link to this project ↗'])}</a></div>
  </article>`;
}

const html = `<!doctype html>
<html lang="zh-CN" data-view="engineering"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="李昊 Hao Li — AI 应用、Agent 开发与技术产品。Story2Game、AI Market Intelligence、AI Social Twin 和 Visual CEP Rule Builder 项目作品集。">
<meta name="color-scheme" content="light"><meta property="og:title" content="Hao Li · Applied AI & Agent Systems"><meta property="og:description" content="Four projects: verifiable generation, evidence, personalized agents and visual rule authoring."><meta property="og:type" content="website">
<title>李昊 · AI 应用与 Agent 开发</title><link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="styles.css"><script defer src="media.js"></script><script defer src="app.js"></script></head>
<body><header class="site-header wrap"><a class="brand" href="#top"><span class="brandmark" aria-hidden="true">h.</span> HAO LI <span class="brand-sub">/ 李昊</span></a><nav aria-label="Main navigation"><a href="#work">${txt(['项目', 'Projects'])}</a><a href="#experience">${txt(['经历', 'Experience'])}</a><a href="#resume">${txt(['简历', 'Résumé'])}</a><button class="language" id="lang-toggle" type="button" aria-label="Switch to English">EN</button><button class="secondary" id="print" type="button">${txt(['保存 PDF', 'Save PDF'])}</button></nav></header>
<main id="top"><section class="hero wrap"><div><div class="eyebrow">APPLIED AI & AGENT SYSTEMS</div><h1>${bi('让 AI 不止于生成。<br>更能<span class="blue">可靠地运行。</span>', 'From AI ideas.<br>To systems<br><span class="blue">that work.</span>')}</h1><p class="intro">${txt(['我是李昊，柏林工业大学计算机工程硕士在读。专注 AI 应用与 Agent 开发，把模型能力转化为可验证、可恢复的实际系统。', 'I’m Hao Li, a Computer Engineering master’s student at TU Berlin. I build AI applications with verifiable execution and recoverable workflows.'])}</p><div class="hero-actions"><a class="primary" href="#work">${txt(['查看项目', 'Explore my work'])}</a><a class="secondary" href="mailto:geemakerlee@gmail.com">${txt(['联系我', 'Get in touch'])}</a></div><div class="hero-meta"><span>${txt(['求职方向：中国 · 德国 · 香港', 'Target markets: China · Germany · Hong Kong'])}</span><span>中文 / English / Deutsch C1</span></div></div>
<div class="system-board"><div class="board-top"><span>THE WAY I BUILD</span><span>HL</span></div><div class="board-title">Probabilistic ideas.<br><span>Deterministic execution.</span></div><div class="pipeline">${[['01', 'Generate', 'Intent → structured output'], ['02', 'Verify', 'Constraints · evidence · tests'], ['03', 'Recover', 'Repair · re-verify · execute']].map(([n, title, sub]) => `<div><span class="number">${n}</span><strong>${title}</strong><small>${sub}</small></div>`).join('')}</div><div class="board-footer"><span>idea → agent → reliable system</span><span>HL / 2026</span></div></div></section>
<div class="expertise-bar"><div class="wrap"><span>LLM APPLICATIONS</span><span>AGENT WORKFLOWS</span><span>RAG & MEMORY</span><span>EVALUATION</span><span>FULL-STACK</span></div></div>
<section class="work-section wrap" id="work"><div class="section-heading"><div><div class="eyebrow">01 / SELECTED WORK</div><h2>${txt(['有想法，也有实现。', 'Built to be understood.'])}</h2><p>${txt(['四个项目，一条主线：让 AI 系统真正可用。', 'Four projects. One focus: making AI useful and reliable.'])}</p></div><div class="role-switch" role="group" aria-label="Project perspective"><button type="button" data-view-button="engineering" aria-pressed="true">${txt(['工程视角', 'Engineering'])}</button><button type="button" data-view-button="product" aria-pressed="false">${txt(['产品视角', 'Product'])}</button></div></div><div class="project-grid">${projects.map(card).join('\n')}</div></section>
<section class="experience-section" id="experience"><div class="wrap experience-grid"><div><div class="eyebrow">02 / EXPERIENCE</div><h2>${bi('从项目原型，<br>到真实业务。', 'From prototypes<br>to real workflows.')}</h2></div><div class="experience-items"><article><div class="item-meta">2025.08 — ${txt(['至今 · 实习', 'PRESENT · INTERNSHIP'])}</div><h3>${txt(['AI 应用工程师', 'AI Application Engineer'])}</h3><h4>${txt(['深圳市麦捷微电子科技股份有限公司', 'Shenzhen Microgate Technology'])}</h4><p>${txt(['企业 RAG、混合检索与部门级 Agent 工作流；结合确定性规则判定与 LLM 解释，改善生产数据处理与异常排查。', 'Enterprise RAG, hybrid retrieval and department-level Agent workflows. Production automation combining deterministic checks with LLM explanations.'])}</p></article><article><div class="item-meta">2023.04 — 2025.06</div><h3>${txt(['软件开发', 'Software Development'])}</h3><h4>TU Berlin · DIMA Lab</h4><p>${txt(['面向流式处理的可视化规则构建：React 交互、类型化 AST、约束验证与执行代码生成。', 'Visual rule authoring for stream processing: React interfaces, typed ASTs, constraint validation and executable rule generation.'])}</p></article></div></div></section>
<section class="about-section wrap" id="resume"><div><div class="eyebrow">03 / RÉSUMÉ</div><h2>${bi('用工程实现，<br>以用户为起点。', 'Engineering<br>with a product mindset.')}</h2></div><div><p>${txt(['关注 AI 应用开发、Agent 开发、AI 全栈，以及强调技术理解与落地能力的 AI 产品岗位。', 'Interested in AI application engineering, Agent development, AI full-stack and technical AI product roles.'])}</p><div class="about-details"><div><small>${txt(['教育背景', 'EDUCATION'])}</small><strong>TU Berlin · Computer Engineering</strong><span>${txt(['硕士 · 2023.10–2026.10（预计）', 'Master’s · 2023.10–Oct 2026 (expected)'])}</span><span>${txt(['本科 · 2018.10–2024.07', 'Bachelor’s · 2018.10–July 2024'])}</span></div><div><small>TOOLBOX</small><strong>Python · SQL · FastAPI · PostgreSQL</strong><span>Java · C/C++ · TypeScript</span><span>React / Next.js · Docker · Linux · Git · Flink</span><span>LLM / RAG · Tool Calling · Multi-Agent</span><span>Memory · Evaluation</span></div></div></div></section>
<section class="contact-section wrap"><div><div class="eyebrow">LET’S BUILD SOMETHING USEFUL</div><h2>${txt(['期待一起，把想法做成产品。', 'Have a role in mind?'])}</h2></div><a class="primary" href="mailto:geemakerlee@gmail.com">geemakerlee@gmail.com</a></section></main><footer class="wrap"><span>© 2026 HAO LI</span><a href="https://github.com/GeeMakerLee" rel="noopener noreferrer">GitHub · GeeMakerLee</a><span>Applied AI & Agent Systems</span></footer></body></html>\n`;
writeFileSync(resolve(root, 'docs/index.html'), html);

for (const p of projects) {
  const md = `# ${p.name}\n\n**${p.title[0]} · ${p.title[1]}**\n\n${p.summary[0]}\n\n${p.summary[1]}\n\n![${p.name} architecture and data flow](../assets/diagrams/${p.slug}.svg)\n\n${sections.map(([zh, en, key]) => `## ${zh} / ${en}\n\n${p[key][0]}\n\n${p[key][1]}\n`).join('\n')}\n## 当前实现 / Current implementation\n\n${p.state[0]}\n\n${p.state[1]}\n\n**Stack / Focus:** ${p.tags.join(' · ')}\n\n<!-- 在取得真实公开截图后，可在这里引用 ../assets/screenshots/ 下的图片。 -->\n\n[返回主页 / Profile](../../README.md) · [项目网站 / Website](${pages}#${p.slug}) · [English case study](${pages}?lang=en#${p.slug})\n`;
  writeFileSync(resolve(root, `docs/projects/${p.slug}.md`), md);
}

const md = `# 李昊 · Hao Li\n\n**AI 应用开发 · Agent Systems · Technical AI Product**\n\n我把模型能力转化为可验证、可恢复的实际系统。\n\nI build LLM applications with verifiable execution, recoverable workflows and useful interfaces.\n\n- 柏林工业大学计算机工程硕士在读，预计 **2026.10** 毕业 / TU Berlin, expected Oct 2026.\n- 企业 **RAG、Hybrid Search、Tool Calling、Multi-Agent** 工作流经验。\n- 求职方向：**AI 应用开发、Agent 开发、AI 全栈、技术型 AI 产品岗位**。\n- 中国为主，德国 / 香港为辅 · Chinese / English / German C1.\n- 联系 / Contact: **geemakerlee@gmail.com**\n\n[中英文项目网站 / Portfolio](${pages}) · [English](${pages}?lang=en) · [现有作品集 / Current portfolio](https://hao-li-portfolio.geemakerlee.chatgpt.site/)\n\n## Selected projects / 精选项目\n\n| 项目 | 解决的问题 | 工程重点 |\n| --- | --- | --- |\n${projects.map(p => `| [**${p.name}**](docs/projects/${p.slug}.md) | ${p.title[0]} | ${p.tags.join(' · ')} |`).join('\n')}\n\n${projects.map(p => `### ${p.name}\n\n${p.summary[0]}\n\n${p.summary[1]}\n\n**我的贡献 / Contribution：** ${p.work[0]}\n\n![${p.name} architecture and data flow](docs/assets/diagrams/${p.slug}.svg)\n\n[项目详解 / Case study](docs/projects/${p.slug}.md) · [查看全图 / Full-size diagram](docs/assets/diagrams/${p.slug}.svg)\n\n<!-- 真实截图可加入此处；不要创建虚构界面。 -->\n`).join('\n')}\n## How I build\n\n**Generate with models. Validate with explicit rules. Recover with clear state.**\n\n关注模型响应之后的工程环节：结构化输出、约束验证、工具执行、状态一致性、评测和失败恢复。\n\nI focus on the part after an LLM response: structured output, constraints, tool execution, state consistency, evaluation and failure recovery.\n\n## Experience / 经历\n\n**AI 应用工程师实习 · 深圳市麦捷微电子科技股份有限公司**  \n**AI Application Engineer Intern · Shenzhen Microgate Technology**  \n2025.08–Present\n\n企业 RAG 与部门级 Agent：混合检索、Tool Calling、部门知识库隔离；生产自动化中结合任务状态、确定性规则与 LLM 解释。\n\nEnterprise RAG and department-level agents with hybrid retrieval, Tool Calling and isolated knowledge spaces; production automation with task state, deterministic checks and LLM explanations.\n\n**Software Development · TU Berlin DIMA Lab**  \n2023.04–2025.06\n\n可视化 CEP 规则构建、RuleGraph 到类型化 AST、拓扑重构、约束验证与执行代码生成。\n\nVisual CEP rule authoring, graph-to-AST mapping, topological reconstruction, validation and executable rule generation.\n\n## Toolkit\n\n**Backend:** Python · SQL · FastAPI · PostgreSQL · Java · C/C++  \n**AI:** LLM applications · RAG · Multi-Agent · Tool Calling · Memory · Evaluation  \n**Frontend & infrastructure:** TypeScript · React / Next.js · Docker · Linux · Git · Flink\n`;
writeFileSync(resolve(root, 'README.md'), md);
console.log(`Built GitHub profile, ${projects.length} case studies and bilingual static Pages site.`);
